version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb
    networks:
      - grpc-micro_default

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo
    networks:
      - grpc-micro_default
  
  phpmyadmin:
    extends:
      file: ./compose/compose.db.yml
      service: phpmyadmin

  product-api:
    env_file:
      - .env
    image: gritt/product-api
    networks:
      - grpc-micro_default
    build:
        context: .
        dockerfile: Dockerfile
        target: production-product
    working_dir: /usr/src/app
    container_name: product-api
    ports:
    - ${PRODUCT_API_PORT}:${PRODUCT_API_PORT}
    depends_on:
        - mariadb
    environment:
        - DATABASE_URL=${DATABASE_URL}
    command: "npm run start:prod"

  payment-api:
    env_file:
      - .env
    image: gritt/payment-api
    networks:
      - grpc-micro_default
    build:
        context: .
        dockerfile: Dockerfile
        target: production-payment
    working_dir: /usr/src/app
    container_name: payment-api
    ports:
        - ${PAYMENT_API_PORT}:${PAYMENT_API_PORT}
    depends_on:
        - mongo
    environment:
        - MONGO_URI=${MONGO_URI}
        - MONGO_DB=${MONGO_DB}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "npm run start:prod"

  auth-api:
    env_file:
      - .env
    image: gritt/auth-api
    networks:
      - grpc-micro_default
    build:
        context: .
        dockerfile: Dockerfile
        target: production-auth
    working_dir: /usr/src/app
    container_name: auth-api
    ports:
        - ${AUTH_API_PORT}:${AUTH_API_PORT}
    depends_on:
      - mongo
    environment:
        - MONGO_URI=${MONGO_URI}
        - MONGO_DB=${MONGO_DB}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "npm run start:prod"

networks:
  grpc-micro_default:
    external: true
    name: grpc-micro_default