version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo
  
  phpmyadmin:
    extends:
      file: ./compose/compose.db.yml
      service: phpmyadmin

  product-api:
    image: gritt/product-api
    build:
        context: .
        dockerfile: Dockerfile
        target: production-product
    working_dir: /usr/src/app
    container_name: product-api
    ports:
      - ${PRODUCT_API_PORT}:${PRODUCT_API_PORT}
    depends_on:
      - mariadb
      - auth-api
    restart: on-failure:10
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PRODUCT_API_PORT:${PRODUCT_API_PORT}
    command: >
      sh -c "npx prisma migrate dev && npm run seed && npm run start:prod"

  payment-api:
    image: gritt/payment-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production-payment
    working_dir: /usr/src/app
    container_name: payment-api
    ports:
      - ${PAYMENT_API_PORT}:${PAYMENT_API_PORT}
    depends_on:
      - mongo
      - product-api
      - auth-api
    restart: on-failure:10
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "npm run start:prod"

  auth-api:
    image: gritt/auth-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production-auth
    working_dir: /usr/src/app
    container_name: auth-api
    ports:
      - ${AUTH_API_PORT}:${AUTH_API_PORT}
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: >
      sh -c "npm run seed && npm run start:prod"

networks:
  grpc-micro_default:
    external: true
    name: grpc-micro_default