name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_product_api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ zmanthegreat }}
        password: ${{ dckr_pat_-2lCP9sg8-mSANtGmV9UcWbNbig }}
    - name: Build and push Docker image for product-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.product-api
        push: true
        tags: user/product-api:latest

  build_payment:
    needs: build_product_api
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image for payment
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.payment
        push: true
        tags: user/payment:latest
